### Example file for running rems-co in a REMS docker compose stack
# See Also:
# https://github.com/CSCfi/rems/blob/master/docker-compose-config.yml

version: '2'
services:

  app:
    image: cscfi/rems:latest
    mem_reservation: 200m
    mem_limit: 2000m
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./config.edn:/rems/config/config.edn
      - ./example-theme/extra-styles.css:/rems/example-theme/extra-styles.css

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: rems
      POSTGRES_PASSWORD: remspassword
    mem_reservation: 30m
    mem_limit: 150m
    ports:
      - "127.0.0.1:5432:5432"

  rems_co:
    container_name: rems_co
    image: ghcr.io/delocalizer/rems-co:latest
    #ports:
    #  - "8080:8080" if you want to expose the health check endpoint externally
    env_file:
      - .env
    restart: unless-stopped
